import React from 'react'
import Footer from '../../components/Footer'
import Navbar from '../../components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Router from 'next/router'

export default function Index() {
    return (
        <div className=' w-full lg:h-full xl:h-full h-screen bg-[#070A0D] '>
          <Head>
            <title>Log In</title>
            <meta name="description" content="Generated by create next app" /> 
          </Head> 
            <Navbar btn="Sign up" />
          <div className=' w-full py-6 px-6 ' >
            <div className=' w-full flex flex-col justify-center items-center my-12 ' >
              <Image width="300px" height="300px" src="/Landing-page-logo.png" alt='Landing' /> 
              <div className='md:w-[486px] lg:w-[486px] xl:w-[486px] font-Poppins-Regular text-white mt-10 ' > 
                <input placeholder='Username, email or phone number' className='  w-full h-12 rounded-[6px] px-6 bg-[#171F26] ' />
                <input type="password" placeholder='Password' className='  w-full h-12 rounded-[6px] mt-3 px-6 bg-[#171F26] ' /> 
                <button onClick={()=> Router.push("/dashbord")} className=' bg-[#00D1FF] h-[45px] text-[#0F1419] w-full font-Poppins-Bold rounded-[6px] mt-6 ' >Log In</button>
                <Link href="/forgot-password" ><p className=' cursor-pointer font-Poppins-Regular text-[#8CA6BF] mt-3 text-center '>Forgot password?</p></Link>
              </div>
            </div>
          </div>
          <div className='lg:flex xl:flex hidden ' > 
            <Footer />
          </div>
          {/* <button className=' absolute bottom-0 right-0 left-0 bg-[#00D1FF] h-14 text-[#0F1419] w-full font-Poppins-Bold ' >Log In</button> */}
        </div>
    )
} 