import Head from 'next/head'
import React, { Children } from 'react'
import MenuBar from '../DashboardComponent/MenuBar'
import Navbar from '../Navbar'
import {
    Drawer,
    DrawerBody,
    DrawerFooter,
    DrawerHeader,
    DrawerOverlay,
    DrawerContent,
    DrawerCloseButton,
    useDisclosure,
    } from '@chakra-ui/react'

export default function Index({ children }: { children: React.ReactNode }, props: any) {


    const { isOpen, onOpen, onClose } = useDisclosure()
    const btnRef = React.useRef()

    return (
        <div className=' w-full h-screen overflow-hidden bg-[#070A0D] '>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" /> 
            </Head> 
            <Navbar dashboard={true} side={onOpen} />
            <div className=' w-full flex flex-1 lg:h-[85vh] h-full overflow-y-auto lg:px-8 xl:px-[328px] px-4 ' >
                <div className=' w-fit ' >
                    <div className=' w-[330px] h-full lg:block hidden overflow-y-auto overflow-x-hidden ' >
                        <MenuBar />
                    </div>
                </div>  
                <Drawer
                    isOpen={isOpen}
                    placement='right'
                    onClose={onClose}  >
                    <DrawerOverlay />
                    <DrawerContent>
                        <DrawerCloseButton color="white" /> 
                        <DrawerBody style={{ background: "#0F1419"}} > 
                        <div className=' w-[330px] h-full overflow-y-auto bg-[#0F1419] overflow-x-hidden ' >
                            <MenuBar />
                        </div>
                        </DrawerBody>
                    </DrawerContent>
                </Drawer>  
                <div className=' flex flex-1 h-full pb-4 ' > 
                    {children} 
                </div>
            </div>
        </div>
    )
}  