import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar' 
import { Player } from '@lottiefiles/react-lottie-player';
import FilesOne from "../lottie-files/Mobile Home.json"
import FilesTwo from "../lottie-files/Resulted Game.json"
import FilesThree from "../lottie-files/Stack Page.json"
import FilesFour from "../lottie-files/Leaderboard.json"

const Home: NextPage = () => {

  const [tab, setTab] = React.useState(1)

  return (
    <div className=' w-screen h-full flex flex-col bg-[#070A0D] '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head> 
      <div className=' w-screen absolute bg-transparent z-10 top-0 inset-x-0 ' > 
        <Navbar btn="Log in / Sign up" />
      </div>
      <div className=' w-screen   ' >
        <div className=' w-full flex flex-col justify-center items-center mb-12 ' >
          <div className=' w-full flex mb-6 bg-gradient-to-r from-[#070A0D] via-[#070A0D]  to-[#00D1FF] pt-24 pb-0 px-6  ' >
            <div className=' w-full flex flex-col relative z-10 items-center px-2 ' > 
              <img src="/Landing-page-logo.png" alt="Landing" className=' lg:w-[424px] w-full lg:h-[424px]' />
              {/* <Image width="424px" height="424px" src="/Landing-page-logo.png" alt='Landing' /> */}
              <p className=" lg:text-3xl xl:text-3xl text-2xl text-center mt-10 text-[#00D1FF] font-Poppins-Bold "  >Fantasy Sports of Sports gaming</p> 
              <p className=" lg:text-xl xl:text-xl mt-4 text-[#8CA6BF] font-Poppins-Bold "  >Players vs Players</p>
              <div className=' w-full flex justify-center items-center my-8 font-Poppins-Bold px-8  ' > 
                <button className=' bg-[#00D1FF] h-[45px] text-[#0F1419] w-full md:w-[153px] lg:w-[153px] xl:w-[153px] text-sm rounded-full mr-4 ' >View Games</button>
                <button className=' border border-[#00D1FF] text-[#00D1FF] h-[45px] bg-[#0F1419] w-full md:w-[153px] lg:w-[153px] xl:w-[153px] text-sm rounded-full ml-4 ' >How To Play</button>
              </div>
            </div>
            <div className=' w-full lg:flex flex-col hidden items-center px-2 ' > 
              <img src="/SideImage.png" alt="SideBar" className=' w-[500px] ' />
            </div>
          </div>
          <div className=' w-full px-6 flex flex-col items-center mt-8 ' >   
              <p className=' text-[#00D1FF] text-2xl text-center font-Poppins-Bold ' >How to play</p>
              <div className=' flex items-center my-5  ' >
                {tab !== 1 ? 
                  <button onClick={()=> setTab((prev) => prev-1)} className=' lg:block hidden font-Poppins-Bold w-[112px] rounded-3xl h-[45px] bg-[#00D1FF] ' >{"<< Step "+(tab-1)}</button>:
                  <div className=' w-[112px] bg-transparent lg:block hidden ' />
                }
                <div className=' w-full lg:w-[500px] bg-[#00D1FF] mx-4 font-Poppins-SemiBold text-lg text-[#0F1419] rounded-2xl py-4 px-6 ' >
                  {tab === 1 && (
                    <>
                      <p className=' text-center ' >Step{" "+tab}</p>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Select a game</p>
                      </div>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Every game has a prize money (Jackpot), number of participants, number of winners, and an entry fee</p>
                      </div>
                    </>
                  )}
                  {tab === 2 && (
                    <>
                      <p className=' text-center ' >Step{" "+tab}</p>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Every game has predictions in it</p>
                      </div>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Assign points to all the  predictions in the game as you see fit</p>
                      </div>
                    </>
                  )}
                  {tab === 3 && (
                    <>
                      <p className=' text-center ' >Step{" "+tab}</p>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Some predictions will <span className=' text-[#006635] ' >”happen”</span> some <span className=' text-[#CC0C0C] ' >”won’t happen”</span></p>
                      </div>
                      <div className=' flex my-[2px]' >
                        <div className=' w-[6px] h-[6px] mr-3 rounded-full bg-[#0F1419] '  />
                        <p className=' ' >Points you give to predictions that did “not happen” are <span className=' text-[#CC0C0C] ' >lost</span></p>
                      </div>
                      <div className=' flex my-[2px]' >
                        <div className=' w-[6px] h-[6px] mr-3 rounded-full bg-[#0F1419] '  />
                        <p className=' ' >Points you give to predictions that “happened” become your <span className=' text-[#006635] ' >score</span></p>
                      </div>
                    </>
                  )}
                  {tab === 4 && (
                    <>
                      <p className=' text-center ' >Step{" "+tab}</p>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Every player is ranked according to their score</p>
                      </div>
                      <div className=' flex my-[2px]' >
                        <div className=' w-fit mt-3 mr-3 ' > 
                          <div className=' w-[6px] h-[6px] rounded-full bg-[#0F1419] '  />
                        </div> 
                        <p className=' ' >Players in the “winning positions” win their share of the Jackpote</p>
                      </div>
                    </>
                  )}
                </div>
                {tab !== 4 ? 
                  <button onClick={()=> setTab((prev) => prev+1)} className=' lg:block hidden font-Poppins-Bold w-[112px] rounded-3xl h-[45px] bg-[#00D1FF] ' >{" Step "+(tab+1)+" >>"}</button>:
                  <div className='w-[112px] bg-transparent lg:block hidden ' />
                }
              </div> 
              <div className=" w-full flex mb-6 justify-center lg:hidden " >
                {tab !== 1 ? 
                  <button onClick={()=> setTab((prev) => prev-1)} className=' mr-2 font-Poppins-Bold w-[112px] rounded-3xl h-[45px] bg-[#00D1FF] ' >{"<< Step "+(tab-1)}</button>:
                  <div className='w-[112px] bg-transparent ' />
                }
                {tab !== 4 ? 
                  <button onClick={()=> setTab((prev) => prev+1)} className=' ml-2 font-Poppins-Bold w-[112px] rounded-3xl h-[45px] bg-[#00D1FF] ' >{" Step "+(tab+1)+" >>"}</button>:
                  <div className='w-[112px] bg-transparent ' />
                }
              </div>
                {tab === 1 && ( 
                  <Player
                    autoplay
                    loop
                    src={FilesOne} className=" w-full lg:w-[500px] h-[860px] " />  
                )}
                {tab === 2 && ( 
                  <Player
                    autoplay
                    loop
                    src={FilesThree} className=" w-full lg:w-[500px] h-[860px] " />  
                )}
                {tab === 3 && ( 
                  <Player
                    autoplay
                    loop
                    src={FilesTwo} className=" w-full lg:w-[500px] h-[860px] " />  
                )}
                {tab === 4 && ( 
                  <Player
                    autoplay
                    loop
                    src={FilesFour} className=" w-full lg:w-[500px] h-[860px] " />  
                )}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Home
