import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import HeroSection from '../components/HomeComponent/HeroSection'
import SecondSection from '../components/HomeComponent/SecondSection'

export default function index() {
    return (
        
    <div className=' w-full lg:h-full xl:h-full h-screen bg-[#070A0D] '> 
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" /> 
        </Head> 
        <div className='absolute bg-transparent z-10 top-0 inset-x-0 ' > 
            <Navbar btn="Log in / Sign up" />
        </div> 
        <div className=' w-full ' >
            <HeroSection />
        </div>
        <div className=' w-full ' >
            <SecondSection />
        </div>
        <Footer />
    </div>
    )
}
