import Head from 'next/head'
import React from 'react'
import GameDetails from '../../components/DashboardComponent/GameDetails'
import MenuBar from '../../components/DashboardComponent/MenuBar'
import SelectedGame from '../../components/DashboardComponent/SelectedGame'
import Navbar from '../../components/Navbar'

export default function Index() {
    return (
        <div className=' w-full h-screen overflow-hidden bg-[#070A0D] '>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" /> 
            </Head> 
            <Navbar />
            <div className=' w-full flex flex-1 h-[85vh] lg:px-14 xl:px-[328px] pb-1 px-8 ' >
                <div className=' w-[300px] h-full overflow-y-auto overflow-x-hidden ' >
                    <MenuBar />
                </div>
                <div className=' flex flex-1 h-full px-5 overflow-y-auto  ' >
                    <GameDetails />
                </div>
                <div className=' flex flex-1 h-full overflow-y-auto  ' >
                    <SelectedGame />
                </div> 
            </div>
        </div>
    )
} 